version: '3.8'
services:
  health_monitor:
    build: ./health_monitor
    ports:
      - "5001:5001"
    depends_on:
      - dummy_service_a
      - dummy_service_b

  dummy_service_a:
    build: ./dummy_service_a
    ports:
      - "5002:5000"

  dummy_service_b:
    build: ./dummy_service_b
    ports:
      - "5003:5000"